image: Ubuntu

environment:
  expected_default_node: v4.
  expected_lts_node: v8.
  expected_current_node: v8.
  expected_stable_node: v9.


test_script:
#- sh: echo "Test!"
#- ps: exit 1
- sh: ls /bin -al
#- sh: exit 1
- sh: |
    . $HOME/.nvm/nvm.sh
    echo Current
    nvm use current
    nv=$(node --version)
    echo $nv
    if [[ $nv =~ ^$expected_current_node ]]; then
        echo "Current Node.js version is Correct"
    else
        echo "Current Node.js version should be ${expected_current_node}.x"
        exit 3
    fi
#- sh: false
- sh: |
    . $HOME/.nvm/nvm.sh
    echo Default
    nv=$(node --version)
    echo $nv
    if [[ $nv =~ ^$expected_default_node ]]; then
        echo "Default Node.js version is Correct"
    else
        echo "Default Node.js version should be ${expected_default_node}.x"
        exit 1
    fi

artifacts:
  - path: '**\*.txt'
  
on_failure:
- sh: echo Failure!

on_success:
- sh: echo Success!

build: off
