build_cloud: LinuxGCE
image: Linux GCE

environment:
  expected_default_node: v4.
  expected_lts_node: v8.
  expected_current_node: v9.
  expected_stable_node: v9.


test_script:
    - sh:
        echo Default
        nv=$(node --version)
        echo $nv
        if [ $nv =~ "^$expected_default_node" ]; then
            echo "Default node version is Correct"
        else
            echo "Default Node.js version should be ${expected_default_node}.x"
            exit 1
    fi

    - sh: |
        . $HOME/.nvm/nvm.sh
        versions=( "9.5.0" "8.9.4" "7.10.1" "6.12.3" "5.12.0" "4.8.7" )
        for version in ${versions[@]}; do
            nvm use ${version}
            node --version >${APPVEYOR_BUILD_FOLDER}/${version}.txt
            if [ $(node --version) = "v${version}" ]; then
                echo "Correct version ${version}"
            else
                exit 1
            fi
        done

artifacts:
  - path: '**\*.txt'

build: off